###############################################################################
# © Copyright IBM Corporation 2020
# Contributed by the Ansible Content for IBM Z Team
#
###############################################################################

- hosts: zos_host
  collections:
    - ibm.ibm_zos_core
  gather_facts: no
  environment: "{{ environment_vars }}"
  vars:
    git_addr: "git://github.com/IBM/z_ansible_collections_samples.git"
    git_branch: "playbook/2926/zos_apf"
    checkout_dir: "{{ home_dir }}/git_checkout/z_ansible_collections_samples"
    file_name: "{{ checkout_dir }}/zos_concepts/program_authorization/git_apf/roles/list-load/files/list.bom"
    persistent_ds: 
      data_set_name: "APFTEST.SYS1.PARMLIB(PROG00)"

  tasks:
    - name: Get home directory
      shell: "echo \"$HOME\" "
      register:  result
    - name: Set home_dir path
      set_fact:
        home_dir: "{{ result.stdout }}"
    - name: Git clone repository
      include_role:
        name: git-pull
    - name: Get current APF list
      include_role:
        name: apf-list
    - name: Load the list from the file in git repo and find out the delta from current APF list
      include_role:
        name: list-load
    - name: Create datasets if not exist
      shell: "dls {{ item['library'] }}  > /dev/null 2>&1 || dtouch -tseq -V{{ item.get('volume', None) }} {{ item['library'] }}"
      loop: "{{ add_list }}"
    - name: Create persistent dataset if not exist
      shell: "dls `echo \"{{ persistent_ds['data_set_name'] }}\" | sed s'/(.*)$//'` > /dev/null 2>&1 || dtouch `echo \"{{ persistent_ds['data_set_name'] }}\" | sed s'/(.*)$//'` }}"
    - name: APF add delta list
      include_role:
        name: apf-add
    - name: APF list to be added
      debug:
        msg: "{{ add_list }}"