# Copyright (c) IBM Corporation 2020

- hosts: zos_host
  collections:
    - ibm.ibm_zos_core
  gather_facts: no
  environment: "{{ environment_vars }}"

  tasks:
    - name: Add user to z/OS system
      include_role:
        name: add-zos-user