###############################################################################
# © Copyright IBM Corporation 2020
# Contributed and supported by the Ansible Content for IBM Z Team
###############################################################################

###############################################################################
# Requirements:
#     - IBM z/OS core collection 1.x.x or later
###############################################################################

###############################################################################
# Changelog
#  All notable changes to this sample will be documented in this playbook
#
# [1.0.0] - 2020-09-01
#  - Released initial version
###############################################################################

- hosts: localhost
  gather_facts: no

  tasks:
    - name: Send a rejection email to the user who requested a new UserID
      mail:
        host: "{{ smtp_server }}"
        port: "{{ smtp_port }}"
        username: "{{ smtp_username }}"
        password: "{{ smtp_password }}"
        to: "{{ email_to }}"
        subject: Request for New UserID was Rejected
        body: "Your request for a new UserID was rejected. Please contact your system administrator if you have further questions."
        secure: always
      no_log: true
