---
# Copyright (c) IBM Corporation 2020

# tasks file for allocate_smpe_datasets
- name: ALLOCATING SMPE Logs
  ibm.ibm_zos_core.zos_data_set:
    name: "{{ smpe_hlq}}.{{item}}"
    type: seq
    record_format: vb
    record_length: 3200
    space_primary: 5
    space_type: M
    key_length: 24
    key_offset: 0
    state: present
  with_items: "{{ smp_datasets.smp_logs }}"

- name: ALLOCATING SMPE LTS
  ibm.ibm_zos_core.zos_data_set:
    name: "{{ smpe_hlq}}.{{item}}"
    type: library
    record_format: u
    record_length: 0
    block_size: 32760
    space_primary: 10
    directory_blocks: 150
    space_type: M
    state: present
  with_items: "{{ smp_datasets.smp_lts }}"

- name: ALLOCATING SMPE PTS
  ibm.ibm_zos_core.zos_data_set:
    name: "{{ smpe_hlq}}.{{item}}"
    type: PDS
    record_format: fb
    record_length: 80
    block_size: 32760
    space_primary: 300
    directory_blocks: 150
    space_type: M
    state: present
  with_items: "{{ smp_datasets.smp_pts }}"

- name: ALLOCATING SMPE PDS
  ibm.ibm_zos_core.zos_data_set:
    name: "{{ smpe_hlq}}.{{item}}"
    type: PDS
    record_format: fb
    record_length: 80
    block_size: 27920
    space_primary: 5
    directory_blocks: 80
    space_type: M
    state: present
  with_items: "{{ smp_datasets.smp_pds }}"
  ignore_errors: true