---
# Copyright (c) IBM Corporation 2021

# tasks file for issue_operator_cmd

##########################################################################
# Issue zos command
##########################################################################
- name: "{{ task_description }}"
  ibm.ibm_zos_core.zos_operator:
    cmd: "{{command}}"



