- name: DB2 Schema Provisioning
  hosts: zsystem
  gather_facts: false
  vars_files:
    - "{{ vars_folder_name }}/db2_schema.yml"
  environment: '{{ system_environment }}'

  tasks:
    - name: DB2 Schema Provisioning
      block:

        # Authenticate user
        - include_role:
            name: db2_login

        # Get the application id
        - include_role:
            name: db2_get_app_id

        # Get the team id and environment id
        - include_role:
            name: db2_get_team_id

        # Get the subsystem id
        - include_role:
            name: db2_get_subsystem_id

        # Create a new instance of an application with/without data
        - include_role:
            name: db2_post_create_instance
          vars:
            with_data: yes

        # Get the status of the newly created instance of an application
        - include_role:
            name: db2_get_status_instance
