- name: De-provisioning of Db2 Schema
  hosts: zsystem
  gather_facts: false
  vars_files:
    - "{{ vars_folder_name }}/db2_schema.yml"
  environment: '{{ system_environment }}'

  tasks:
    - name: Db2 schema De-provision
      block:

        # Authenticate user
        - include_role:
            name: db2_login

        # Delete existing instance of an application    
        - include_role:
            name: db2_delete_app_instance