apiVersion: v1
baseDomain: fpet.pokprv.stglabs.ibm.com
imageContentSources:
- mirrors:
  - intreg0.fpet.pokprv.stglabs.ibm.com:5000/test0/ocp4/openshift4/install
  source: quay.io/openshift-release-dev/ocp-release 
- mirrors:
  - intreg0.fpet.pokprv.stglabs.ibm.com:5000/test0/ocp4/openshift4/install
  source: quay.io/openshift-release-dev/ocp-v4.0-art-dev 
compute:
- architecture: s390x
  hyperthreading: Enabled
  name: worker
  platform: {}
  replicas: 2
controlPlane:
  architecture: s390x
  hyperthreading: Enabled
  name: master
  platform: {}
  replicas: 3
metadata:
  creationTimestamp: null
  name: test0
networking:
  clusterNetworks:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.20.80.0/22
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  none: {}
publish: External
pullSecret: '{"auths":{"intreg0.fpet.pokprv.stglabs.ibm.com:5000": {"auth": "dGVzdDp0ZXN0MA=="}}}'
sshKey: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBlBQw4IBxyn9W2hF+MDTRW21fq91PT3e0fwnKa2aTQz
  fpmitaro@us.ibm.com
additionalTrustBundle: |
  -----BEGIN CERTIFICATE-----
  MIIEuzCCAyOgAwIBAgIBATANBgkqhkiG9w0BAQsFADBGMSQwIgYDVQQKDBtGUEVU
  LlBPS1BSVi5TVEdMQUJTLklCTS5DT00xHjAcBgNVBAMMFUNlcnRpZmljYXRlIEF1
  dGhvcml0eTAeFw0yMTA4MTYxNTA2MjJaFw00MTA4MTYxNTA2MjJaMEYxJDAiBgNV
  BAoMG0ZQRVQuUE9LUFJWLlNUR0xBQlMuSUJNLkNPTTEeMBwGA1UEAwwVQ2VydGlm
  aWNhdGUgQXV0aG9yaXR5MIIBojANBgkqhkiG9w0BAQEFAAOCAY8AMIIBigKCAYEA
  58r05eSLyAlHWu2mMtXUPRareADrIKfumz6O9YSrcxXXXs21P5YsIVMMi79v9DOi
  LWyVdIQ5sX8ABSkIFmvyR0+uryd7zOlFuZJ34eIyQ8hJJVcmIJw+3n8x8sa0HbZ8
  ao3OZz3YrM1svAey4XBINl9won50lrx8asbRC29EJtPE6URrB4qO6Fenx9IZ67nW
  GC8KeXSTliX161PS7JNDcQOb5obtIP7SGjsCVL5xXVfrSPzcc6Kbg1soErpVTJ1u
  ZqI5Bg35duVUdq8nyFNcpPZ0bJcIyT7eN11oh50/gzDc7bgnp2RJJosPl+FDEEXZ
  44QxnioHOiRIngUkCM7dDgrPjdq2PCTiw+YykmR6KThdm0bnZ81Nyso/9CEnWZqU
  DYpbSnO6Gkz/aTdxAZ9b0jKxlsDuPRH0yHUuNCsecUadeOazQyHvr3mecaOCxc2E
  vPLrj8T01n6Un5n1K3AgZ9Qtp3DzxvQmhkBLe183V870FMYnzoVE2R5p9Tanztqb
  AgMBAAGjgbMwgbAwHwYDVR0jBBgwFoAUWl1Gycb6XU6QdKILW25GCvvciRAwDwYD
  VR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAcYwHQYDVR0OBBYEFFpdRsnG+l1O
  kHSiC1tuRgr73IkQME0GCCsGAQUFBwEBBEEwPzA9BggrBgEFBQcwAYYxaHR0cDov
  L2lwYS1jYS5mcGV0LnBva3Bydi5zdGdsYWJzLmlibS5jb20vY2Evb2NzcDANBgkq
  hkiG9w0BAQsFAAOCAYEA545ByUeL8jtRnfGrqQQJuRE/+exUe+/e4sWzASHC6Z/z
  y0rjcM5dMdNYTGiy2lidF4lcBV0mTc28ubO0vZ68MzH4uYT4KObsC0e4xxKO2EH6
  6RL6oJ9f2zKpOu28fcyKRjA74OLb+69354Qpr8TmQhkWRb7tE9hj1OQHrj+uJG+l
  CQzvAKxDBYWqDwAkWhsBXi/EBesCkCXoJDlyE9my8eAndUOLRNDqlFZJPDuasJrZ
  EdQJie9exU+CU1+Hm0oQH3HWsfvSgg/vAUk9MXrTxets0eVY22G5kZKSZvSnN9A7
  oL8PNCuq3BZleSNxgeovoBp3mIMrFfwHIRwu8EL3CeFecV6wOaZrFBRU938mLwVa
  RPPm1I4wxEnqSn9yqLkBiFGbb0o5ELfGMv2zHGiR+wHGYbelbS2ewCLgo/+w690E
  rtlwkB3+yU4Qwld+BiRSb84CvGufVSeZ2abPk7Kf67fLRfKtIHza4hzJwpo6z4wq
  bRaUkgKe6w4n+XYm7WGg
  -----END CERTIFICATE-----

