###############################################################################
# © Copyright IBM Corporation 2020
# Contributed and supported by the Ansible Content for IBM Z Team
###############################################################################

###############################################################################
# Requirements:
#     - IBM z/OS core collection 1.2.0 or later
###############################################################################

###############################################################################
# Changelog
#  All notable changes to this sample will be documented in this playbook
#
# [1.0.0] - 2020-09-01
#  - Released initial version
###############################################################################

- hosts: source_system
  collections:
    - ibm.ibm_zos_core
  gather_facts: no
  environment: "{{ environment_vars }}"

  tasks:
    - name: Dump, pack, and transfer data sets
      include_role:
        name: dump-pack-ftp-data-sets
        public: yes
