- name: Listing DB2 Applications for the specific user
  hosts: zsystem
  gather_facts: false
  vars_files:
    - "{{ vars_folder_name }}/db2_applications.yml"
  environment: '{{ system_environment }}'

  tasks:
    - name: DB2 Schema Provisioning
      block:

        # Authenticate user
        - include_role:
            name: db2_login

        # Get the list of applications
        - include_role:
            name: db2_get_list_apps
