---
# tasks file for db2_login

- name: Authenticate User
  uri:
    url: "zos_target_address:12024/ws/security/login"
    validate_certs: no
    user: "{{ username }}"
    password: "{{ password }}"
    method: POST
    body: '{
        "id": "{{ username }}",
        "password": "{{ password }}"
      }'
    body_format: json
    status_code: 200
  register: basic_auth

- name: Register bearer token
  set_fact:
    ACCESS_TOKEN: "{{basic_auth.json['accessToken']}}"
