################################################################################
# the path to the root of IBM python installation
################################################################################
PYZ: "/var/hamb380/usr/lpp/IBM/cyp/v3r8/pyz"

################################################################################
# the path to root of ZOAU installation
################################################################################
ZOAU: "/var/zoau/1.1.0"

################################################################################
# The environment variables that should be set on z/OS host when running playbook.
# You should not need to change environment_vars
################################################################################
environment_vars:
  _BPXK_AUTOCVT: "ON"
  ZOAU_HOME: "{{ ZOAU }}"
  ZOAU_ROOT: "{{ ZOAU }}"
  PYTHONPATH: "{{ ZOAU }}/lib"
  LIBPATH: "{{ ZOAU }}/lib:{{ PYZ }}/lib:/lib:/usr/lib:."
  PATH: "{{ ZOAU }}/bin:{{ PYZ }}/bin:/bin:/usr/sbin:/var/bin"
  _CEE_RUNOPTS: "FILETAG(AUTOCVT,AUTOTAG) POSIX(ON)"
  _TAG_REDIR_ERR: "txt"
  _TAG_REDIR_IN: "txt"
  _TAG_REDIR_OUT: "txt"
  LANG: "C"

################################################################################
# SMPE specific variables
################################################################################
global_csi: "{{smpe_hlq}}.CSI"
target_zone: 'TGT'
dist_zone: 'DLIB'
smpe_hlq: 'ANDYN.ZOAU100'
storage_class: 'DB2SMS10'
smpe_root: '/u/andyn/var/zoau100'