# =================================================================
# Licensed Materials - Property of IBM
#
# (c) Copyright IBM Corp. 2021 All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
# =================================================================

---
# tasks file for configure-installer-and-image

- name: Download openshift installer
  become: yes
  get_url:
    url: https://mirror.openshift.com/pub/openshift-v4/{{ ansible_architecture }}/clients/ocp/{{ openshift_version }}.{{ openshift_minor_version }}/openshift-install-linux.tar.gz
    dest: .
    mode: 0755

- name: Unzip openshift installer
  command:
    cmd: tar -zvxf openshift-install-linux.tar.gz
  
- name: Remove openshift installer archive
  file:
    state: absent
    path: openshift-install-linux.tar.gz

- name: Download openshift client
  become: yes
  get_url:
    url: https://mirror.openshift.com/pub/openshift-v4/{{ ansible_architecture }}/clients/ocp/{{ openshift_version }}.{{ openshift_minor_version }}/openshift-client-linux.tar.gz
    dest: .
    mode: 0755

- name: Unzip openshift client archive
  command:
    cmd: tar -zvxf openshift-client-linux.tar.gz
  
- name: Remove openshift client archive
  file:
    state: absent
    path: openshift-client-linux.tar.gz