---
################################################################################
# Copyright (c) IBM Corporation 2021
################################################################################

################################################################################
# the path to the root of IBM python installation
################################################################################
PYZ: "/usr/lpp/cyp/v3r8/pyz"
################################################################################
# the path to root of ZOAU installation
################################################################################
ZOAU: "/var/zoau110"

