---
# Copyright (c) IBM Corporation 2020

# defaults file for remove-zos-user

##################################################################################################################
# Specifies the user to be removed from RACF.
##################################################################################################################
userid: ""

##################################################################################################################
# Specifies a RACF-defined user or group that owns the group data set profiles now owned by the
# user to be removed.
# If you omit this operand when group data set profiles exist that require a new owner, RACF does not
# remove the user from the group. (Group data set profiles are data set profiles whose names are qualified
# by the group name or begin with the value supplied by an installation exit.)
# The new owner of the group data set profiles must have at least USE authority in the specified group.
# Do not specify a user who is being removed from the group as the new data set profile owner.
##################################################################################################################
new_owner: ""

##################################################################################################################
# Specifies the user catalog entryname for which an alias is defined.
##################################################################################################################
user_catalog: ""

##################################################################################################################
# Specifies the user's z/OS UNIX initial directory path name.
# This is the current working directory for the user's process when the user enters the TSO/E.
# When you define a HOME directory name to RACF, it can contain 1 - 1023 characters.
# The HOME path name can consist of any characters.
# If left blank, home directory is /u/userid.
##################################################################################################################
omvs_home_directory: ""

##################################################################################################################
# Specifies the name of the data set to be used when removing ZFS data set.
##################################################################################################################
omvs_zfs_data_set_name: ""

##################################################################################################################
# Specifies if the user data sets should be deleted.
# This job attempts to delete any data sets with the HLQ matching the user ID of the user to be removed.
##################################################################################################################
delete_user_data_sets: yes