---
# Sample module-level playbook of the IBM Z HMC Collection

- hosts: localhost
  connection: local
  vars_files:
    - vault.yml
  vars:
    stogroup_name: sample-sg-1
    stovolume_name: sample-sv-1
  collections:
    - ibm.ibm_zhmc
  tasks:

    - name: "Get facts for storage volume {{ stovolume_name }} of storage group {{ stogroup_name }}"
      zhmc_storage_volume:
        hmc_host: "{{ hmc_host }}"
        hmc_auth: "{{ hmc_auth }}"
        cpc_name: "{{ cpc_name }}"
        storage_group_name: "{{ stogroup_name }}"
        name: "{{ stovolume_name }}"
        state: facts
      register: result

    - name: Print the result
      debug:
        var: result
