---
# Sample module-level playbook of the IBM Z HMC Collection

- hosts: localhost
  connection: local
  vars_files:
    - vault.yml
  collections:
    - ibm.ibm_zhmc
  tasks:

    - name: "Get facts for CPC {{ cpc_name }}"
      zhmc_cpc:
        hmc_host: "{{ hmc_host }}"
        hmc_auth: "{{ hmc_auth }}"
        name: "{{ cpc_name }}"
        state: facts
      register: result

    - name: Print the result
      debug:
        var: result
