---
# Sample module-level playbook of the IBM Z HMC Collection

- hosts: localhost
  connection: local
  vars_files:
    - vault.yml
  vars:
    adapter_id: '7c3'  # Adjust to Hipersockets adapter created
    new_adapter_name: sample-hs-1
  collections:
    - ibm.ibm_zhmc
  tasks:

  - name: "Ensure adapter with PCHID {{ adapter_id }} has name {{ new_adapter_name }}"
    zhmc_adapter:
      hmc_host: "{{ hmc_host }}"
      hmc_auth: "{{ hmc_auth }}"
      cpc_name: "{{ cpc_name }}"
      name: "{{ new_adapter_name }}"
      match:
        adapter_id: "{{ adapter_id }}"
      state: set
    register: result

  - name: Print the result
    debug:
      var: result
