###############################################################################
# © Copyright IBM Corporation 2021
# Contributed by the Ansible Content for IBM Z Team
#
# Changelog
#  All notable changes to this sample will be documented in this playbook
#
# 2021-03-31
#  - Released initial version
###############################################################################

###############################################################################
# Requirements:
#     - IBM z/OS core collection 1.2.0 or later
###############################################################################

- hosts: zos_host
  collections:
    - ibm.ibm_zos_core
  gather_facts: no
  environment: "{{ environment_vars }}"

  tasks:
  ###########################################################################
  # ISSUE ALL RACF COMMANDS NEEDED TO ADD CERTIFICATE TO SMP/E RECEIVE ORDER
  # NOTE: USER CERTIFICATE AND CA CERTIFICATE ALREADY IN Z/OS DATA SETS
  ###########################################################################
    - block:
      - name: Define, permit and activate FACILITY class
        zos_mvs_raw:
          pgm: ikjeft01
          auth: yes
          parm: "REGIONS=0K"
          dds:
            - dd_output:
                dd_name: sysprint
                return_content:
                  type: text
            - dd_output:
                dd_name: systsprt
                return_content:
                  type: text
            - dd_output:
                dd_name: sysdump
                return_content:
                  type: text
            - dd_input:
                dd_name: systsin
                content:
                    - RDEFINE FACILITY IRR.DIGTCERT.ADD      UACC(NONE)
                    - RDEFINE FACILITY IRR.DIGTCERT.ADDRING  UACC(NONE)
                    - RDEFINE FACILITY IRR.DIGTCERT.ALTER    UACC(NONE)
                    - RDEFINE FACILITY IRR.DIGTCERT.CONNECT  UACC(NONE)
                    - RDEFINE FACILITY IRR.DIGTCERT.LIST     UACC(NONE)
                    - RDEFINE FACILITY IRR.DIGTCERT.LISTRING UACC(NONE)
                    - PERMIT IRR.DIGTCERT.ADD      CLASS(FACILITY) ID(OMVSADM) ACCESS(READ)
                    - PERMIT IRR.DIGTCERT.ADDRING  CLASS(FACILITY) ID(OMVSADM) ACCESS(READ)
                    - PERMIT IRR.DIGTCERT.ALTER    CLASS(FACILITY) ID(OMVSADM) ACCESS(READ)
                    - PERMIT IRR.DIGTCERT.CONNECT  CLASS(FACILITY) ID(OMVSADM) ACCESS(UPDATE)
                    - PERMIT IRR.DIGTCERT.LIST     CLASS(FACILITY) ID(OMVSADM) ACCESS(READ)
                    - PERMIT IRR.DIGTCERT.LISTRING CLASS(FACILITY) ID(OMVSADM) ACCESS(READ)
                    - RACDCERT ID(OMVSADM) ADDRING(SMPERING)
                    - RACDCERT ID(OMVSADM) LISTRING(SMPERING)
                    - RACDCERT ID(OMVSADM) ADD('IMSTESTL.ZOAU100.SMPE.USER.CERT') +
                    - WITHLABEL('SMPE Client Certificate') PASSWORD('{{user_cert_pwd}}') TRUST
                    - RACDCERT CERTAUTH ADD('IMSTESTL.ZOAU100.SMPE.CA.CERT') +
                    - WITHLABEL('DigiCert Global Root CA') TRUST
                    - RACDCERT ID(OMVSADM) CONNECT(LABEL('SMPE Client Certificate') +
                    - RING(SMPERING) USAGE(CERTAUTH) )
                    - RACDCERT ID(OMVSADM) +
                    - CONNECT( CERTAUTH LABEL('DigiCert Global Root CA') +
                    - RING(SMPERING) USAGE(CERTAUTH) )
                    - RACDCERT CERTAUTH LIST(LABEL('DigiCert Global Root CA'))
                    - RACDCERT ID(OMVSADM) LIST(LABEL('SMPE Client Certificate'))
                    - SETROPTS CLASSACT(DIGTCERT DIGTRING)
                    - SETROPTS RACLIST(FACILITY DIGTCERT DIGTRING) REFRESH

