- name: DB2 Subsystem Discovery
  hosts: zsystem
  gather_facts: false
  vars_files:
    - "{{ vars_folder_name }}/db2_discovery.yml"
  environment: '{{ system_environment }}'

  tasks:
    - name: DB2 Schema Provisioning
      block:

        # Authenticate user
        - include_role:
            name: db2_login

        # Get the application id
        - include_role:
            name: db2_put_infra_discovery

        - include_role:
            name: db2_post_graphql_discovery