# Copyright (c) IBM Corporation 2020

# the path to the root of IBM python installation
PYZ: "/usr/lpp/IBM/cyp/v3r8/pyz"

# the path to root of ZOAU installation
ZOAU: "/usr/lpp/IBM/zoautil"

# you should not need to change environment_vars
environment_vars:
  _BPXK_AUTOCVT: "ON"
  ZOAU_HOME: "{{ ZOAU }}"
  PYTHONPATH: "{{ ZOAU }}/lib"
  LIBPATH: "{{ ZOAU }}/lib:{{ PYZ }}/lib:/lib:/usr/lib:."
  PATH: "{{ ZOAU }}/bin:{{ PYZ }}/bin:/bin:/var/bin"
  _CEE_RUNOPTS: "FILETAG(AUTOCVT,AUTOTAG) POSIX(ON)"
  _TAG_REDIR_ERR: "txt"
  _TAG_REDIR_IN: "txt"
  _TAG_REDIR_OUT: "txt"
  LANG: "C"

# a list of data sets contained in an archive you wish to restore
data_sets_to_restore:
  - "**"

# the name to use for the data set archive
# if not provided, module-generated name will be used
archive_data_set: ""

# the name to use for the tersed archive data set
terse_data_set: ""

# the volume where data sets restored from an archive should be placed
# if output volume not provided system defaults will be used
output_volume: ""

# the HLQ to give to the data sets after restore
# if one is not provided, original will be used
new_hlq: ""

# should terse and archive data sets be deleted upon successful restore?
delete: yes

# should existing data sets be overwritten during restore
replace: yes
