###############################################################################
# © Copyright IBM Corporation 2021
# Contributed by the Ansible Content for IBM Z Team
#
# Changelog
#  All notable changes to this sample will be documented in this playbook
#
# 2021-06-30
#  - Released initial version
###############################################################################

###############################################################################
# Requirements:
#     - IBM z/OS core collection 1.3.0 or later
###############################################################################

- hosts: zos_host
  collections:
    - ibm.ibm_zos_core
  gather_facts: no
  environment: "{{ environment_vars }}"
  vars:
    owner_id: 'OMVSKERN'
    ca_cert_label: 'ANDYCA'
    site_cert_label: 'ANDYSITE'

  tasks:
  - include_role:
      name: issue_racf_cmd
    vars:
      task_description: 'Create a new keyring'
      command:
          - RACDCERT ID({{ owner_id}}) DELETE(LABEL('{{site_cert_label}}'))
          - RACDCERT CERTAUTH DELETE(LABEL('{{ca_cert_label}}'))
          - RACDCERT DELRING(SharedRing1) ID({{owner_id}})
          - RACDCERT ADDRING(SharedRing1) ID({{owner_id}})
          - RACDCERT LISTRING(SharedRing1) ID({{owner_id}})

  - include_role:
      name: issue_racf_cmd
    vars:
      task_description: 'Create new certs and connect to keyring'
      command:
        - RACDCERT GENCERT CERTAUTH KEYUSAGE(CERTSIGN) +
        - SUBJECTSDN(CN('TN3270 CA') OU('ANSIBLE CORE') +
        - C('US')) WITHLABEL('{{ca_cert_label}}')
        - RACDCERT ID({{owner_id}}) +
        - CONNECT(CERTAUTH LABEL('{{ca_cert_label}}') +
        - RING(SharedRing1))
        - RACDCERT SITE GENCERT ID({{owner_id}}) +
        - SUBJECTSDN(CN('ec01129a.vmec.svl.ibm.com') +
        - OU('ANSIBLE CORE') C('US')) +
        - WITHLABEL('{{site_cert_label}}')  +
        - SIGNWITH(CERTAUTH LABEL('{{ca_cert_label}}')) +
        - NOTAFTER(DATE(2021-05-28))
        - RACDCERT LISTCHAIN (LABEL('{{site_cert_label}}')) +
        - ID({{owner_id}})
        - RACDCERT ID({{owner_id}}) +
        - CONNECT(LABEL('{{site_cert_label}}') +
        - RING(SharedRing1) DEFAULT USAGE(PERSONAL))
        - RACDCERT LISTRING(SharedRing1) ID({{owner_id}})

  - include_role:
      name: issue_operator_cmd
    vars:
      task_description: 'Stop TN3270 server'
      command: 'p TN3270'

  - include_role:
      name: issue_operator_cmd
    vars:
      task_description: 'Start TN3270 server'
      command: 's TN3270'

  - include_role:
      name: issue_operator_cmd
    vars:
      task_description: 'Run Health Checker'
      command: "F HZSPROC,RUN,CHECK=(IBMRACF,RACF_CERTIFICATE_EXPIRATION)"


