###############################################################################
# © Copyright IBM Corporation 2021
# Contributed by the Ansible Content for IBM Z Team
#
# Changelog
#  All notable changes to this sample will be documented in this playbook
#
# 2021-04-30
#  - Released initial version
###############################################################################

###############################################################################
# Requirements:
#     - IBM z/OS core collection 1.3.0 or later
###############################################################################

- hosts: zos_host
  collections:
    - ibm.ibm_zos_core
  gather_facts: no
  environment: "{{ environment_vars }}"

  roles:
    - role: issue_racf_cmd
      system_name: 'EC01129A'
      task_description: 'Delete certs'
      command:
       - RACDCERT ID({{ ansible_user}}) DELETE(LABEL('WEB SERVER CERT'))
       - RACDCERT LIST(LABEL('WEB SERVER CERT'))
       - RACDCERT CERTAUTH DELETE(LABEL('TEST CA CERT'))
       - RACDCERT CERTAUTH LIST(LABEL('TEST CA CERT'))