- hosts: zos_host
  collections:
    - ibm.ibm_zos_core
  gather_facts: no
  environment: "{{ environment_vars }}"
  tasks:
    # - name: Execute TSO command list user TESTUSER to obtain TSO information
    #   zos_tso_command:
    #     commands:
    #        - LU
    #        - TIME
    #   register: result

    # - name: debug
    #   debug:
    #     msg: '{{result}}'

    - name: Execute TSO command
      zos_tso_command:
        commands:
           - RACDCERT CERTAUTH LIST(LABEL('ANDY CA'))
           - LU
      register: result

    # - name: debug
    #   debug:
    #     msg: '{{result}}'

    - include_role:
        name: issue_racf_cmd
      vars:
        task_description: 'test mvs_raw'
        command:
          - RACDCERT CERTAUTH LIST(LABEL('ANDY CA'))
          - LU

    # - name: Execute IEFBR14
    #   zos_mvs_raw:
    #     program_name: IEFBR14
    #     # dds:
    #     #   - dd_dummy:
    #     #       dd_name: sysprint
    #   register: result
    # - name: Command Output
    #   debug:
    #     msg: "{{ result }}"

    # - name: Test mvs_raw with ikjeft01/TSO commands

    #   zos_mvs_raw:

    #     pgm: ikjeft01

    #     auth: yes

    #     parm: "REGIONS=0K"

    #     dds:

    #       - dd_output:

    #           dd_name: sysprint

    #           return_content:

    #             type: text

    #       - dd_output:

    #           dd_name: systsprt

    #           return_content:

    #             type: text

    #       - dd_output:

    #           dd_name: sysdump

    #           return_content:

    #             type: text

    #       - dd_input:

    #           dd_name: systsin

    #           content:

    #             - HELP

    #             - TIME

    #   register: cmds_rc