###############################################################################
# © Copyright IBM Corporation 2021
# Contributed by the Ansible Content for IBM Z Team
#
# Changelog
#  All notable changes to this sample will be documented in this playbook
#
# 2021-04-30
#  - Released initial version
###############################################################################

###############################################################################
# Requirements:
#     - IBM z/OS core collection 1.3.0 or later
###############################################################################

- hosts: zos_host
  collections:
    - ibm.ibm_zos_core
  gather_facts: no
  environment: "{{ environment_vars }}"
  vars:
    cert_label: 'ANDY SERVER CERT'

  tasks:

    # - name: 'Delete cert with label {{cert_label}}'
    - include_role:
        name: issue_racf_cmd
      vars:
          system_name: 'EC01129A'
          task_description: 'Delete certs'
          command:
          - RACDCERT ID({{ ansible_user}}) DELETE(LABEL('{{cert_label}}'))
          - RACDCERT LIST(LABEL('{{cert_label}}'))

    # - name: 'Delete keyring'
    - include_role:
        name: issue_racf_cmd
      vars:
          system_name: 'EC01129A'
          task_description: 'Delete keyring'
          command:
          - RACDCERT DELRING(WEBSSL)
          - RACDCERT LISTRING(WEBSSL)


