###############################################################################
# © Copyright IBM Corporation 2021
# Contributed by the Ansible Content for IBM Z Team
#
# Changelog
#  All notable changes to this sample will be documented in this playbook
#
# 2021-06-30
#  - Released initial version
###############################################################################

###############################################################################
# Requirements:
#     - IBM z/OS core collection 1.3.0 or later
###############################################################################

- hosts: zos_host
  collections:
    - ibm.ibm_zos_core
  gather_facts: no
  environment: "{{ environment_vars }}"
  vars:
    owner_id: 'OMVSADM'
    cert_type: 'USER'
    cert_label: 'ANDY SSL'

    # cert_type: 'CERTAUTH'
    # cert_label: 'ANDY CA'

    # cert_type: 'SITE'
    # cert_label: 'ANDY SITE'

    check_name: 'IBMRACF,RACF_CERTIFICATE_EXPIRATION'

  tasks:
  - include_role:
      name: issue_tso_cmd
    vars:
      task_description: 'Deleting cert {{cert_label}}'
      command:
          - RACDCERT ID({{ owner_id}}) DELETE(LABEL('{{cert_label}}'))
    when: cert_type == 'USER'

  - include_role:
      name: issue_tso_cmd
    vars:
      task_description: 'Deleting cert {{cert_label}}'
      command:
          - RACDCERT CERTAUTH DELETE(LABEL('{{cert_label}}'))
    when: cert_type == 'CERTAUTH'

  - include_role:
      name: issue_tso_cmd
    vars:
      task_description: 'Deleting cert {{cert_label}}'
      command:
          - RACDCERT SITE DELETE(LABEL('{{cert_label}}'))
    when: cert_type == 'SITE'

  - include_role:
      name: issue_operator_cmd
    vars:
      task_description: 'Run Health Checker'
      command: "F HZSPROC,RUN,CHECK=({{check_name}})"


