---
# Sample module-level playbook of the IBM Z HMC Collection

- hosts: localhost
  connection: local
  vars_files:
    - vault.yml
  vars:
    partition_name: sample-part-1
    crypto_adapters: [CRYP00, CRYP01]
  collections:
    - ibm.ibm_zhmc
  tasks:

    - name: "Ensure domains 2..max on crypto adapters {{ crypto_adapters }} are attached to partition {{ partition_name }}"
      zhmc_crypto_attachment:
        hmc_host: "{{ hmc_host }}"
        hmc_auth: "{{ hmc_auth }}"
        cpc_name: "{{ cpc_name }}"
        partition_name: "{{ partition_name }}"
        state: attached
        crypto_type: ep11
        adapter_names: {{ crypto_adapters }}
        domain_range: 2,-1
        access_mode: usage
      register: result

    - name: Print the result
      debug:
        var: result
